Diploma review
tank4gun/GophKeeperDiploma pull request #1
Opened 2023-05-17 23:33 UTC by tank4gun

2023-05-20 08:24 UTC, kilchik requested changes

2023-05-20 08:24 UTC, kilchik commented on cmd/client/main.go
> +			sigChan <- syscall.SIGTERM
По-хорошему здесь нужно дождаться, пока завершится обработчик. Например, клиент начал отправку нового секрета, и тут пришел сигнал от ОС о завершении - хорошо бы дать время клиенту завершить отправку

2023-05-20 08:24 UTC, kilchik commented on internal/server/handlers/grpc_handlers.go
> +		data, err := Encrypt(dataBytes, clientToken)
Ошибки нельзя игнорировать, у тебя почти все ошибки в хэндлерах игнорируются. Все ошибки должны обрабатываться на каждом уровне, где они были получены: либо оборачиваем с префиксом, либо создаем новый тип ошибки. До клиента должны доходить не ошибки, сформированные слоем сохранения данных, а ошибки, подготовленные контроллером специально для клиента (это может быть набор уникальных кодов или ошибки с описанием)

2023-05-20 08:24 UTC, kilchik commented on internal/server/handlers/grpc_handlers.go
> +		meta, err := Encrypt(metaBytes, clientToken)
и тут ты тоже не обрабатываешь ошибки

2023-05-21 13:55 UTC, tank4gun commented on cmd/client/main.go
> +			sigChan <- syscall.SIGTERM
У меня же все запросы клиента отправляются синхронно, т.е. пока мы не получили ответ от сервера для очередного запроса, пользователь не может вводить новую команду. Т.к. `exit` - это именно команда, пользователь может ее ввести только при условии, что все предыдущие команды завершились.

2023-05-29 13:27 UTC, kilchik commented on cmd/client/main.go
> +			sigChan <- syscall.SIGTERM
Пользователь ведь в любой момент может нажать ctrl+c, а операционка при ребуте послать сигнал о завершении

2023-05-29 13:28 UTC, kilchik approved these changes

2023-05-30 20:46 UTC, merged